services:
  api-gateway:
    build: ./gateway
    container_name: api-gateway
    environment:
      - GATEWAY_PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:8001
      - ACCOUNT_SERVICE_URL=http://account-service:8002
      - TRANSACTION_SERVICE_URL=http://transaction-service:8003
      - CORS_ORIGINS=*
      - JWT_SECRET=dev-change-me
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - account-service
      - transaction-service

  auth-service:
    build: ./auth_service
    container_name: auth-service
    environment:
      - SERVICE_PORT=8001
      - CORS_ORIGINS=*
      - JWT_SECRET=dev-change-me
      - DATABASE_URL=sqlite:///./auth.db
    volumes:
      - auth_db:/app
    ports:
      - "8001:8001"

  account-service:
    build: ./account_service
    container_name: account-service
    environment:
      - SERVICE_PORT=8002
      - CORS_ORIGINS=*
      - DATABASE_URL=sqlite:///./accounts.db
    volumes:
      - accounts_db:/app
    ports:
      - "8002:8002"

  transaction-service:
    build: ./transaction_service
    container_name: transaction-service
    environment:
      - SERVICE_PORT=8003
      - CORS_ORIGINS=*
      - DATABASE_URL=sqlite:///./transactions.db
      - ACCOUNT_SERVICE_URL=http://account-service:8002
    volumes:
      - transactions_db:/app
    ports:
      - "8003:8003"
    depends_on:
      - account-service

volumes:
  auth_db:
  accounts_db:
  transactions_db:
